
SET NAME utf8mb4_0900_ai_ci;

CREATE TABLE Users (
	id SMALLINT unsigned NOT NULL AUTO_INCREMENT,
	firstname VARCHAR(120) NOT NULL,
	lastname VARCHAR(120) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	isadmin TINYINT NOT NULL,
	PRIMARY KEY(id),
	UNIQUE KEY ind_uni_email (email)
) ENGINE=INNODB;

CREATE TABLE Posts (
	id MEDIUMINT unsigned NOT NULL AUTO_INCREMENT,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id SMALLINT unsigned,
	imageurl VARCHAR(255),
	content TEXT,
	PRIMARY KEY(id)
) ENGINE=INNODB;

CREATE TABLE Comments (
	id INT unsigned NOT NULL AUTO_INCREMENT,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	content TEXT NOT NULL,
	user_id SMALLINT unsigned,
	post_id MEDIUMINT unsigned NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Likes (
	id INT unsigned NOT NULL AUTO_INCREMENT,
	rate TINYINT NOT NULL,
	user_id SMALLINT unsigned NOT NULL,
	post_id MEDIUMINT unsigned NOT NULL,
	PRIMARY KEY(id)
);

ALTER TABLE Posts ADD CONSTRAINT fk_Posts_Users_id FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE SET NULL UPDATE CASCADE;
ALTER TABLE Comments ADD CONSTRAINT fk_Comments_Users_id FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE SET NULL UPDATE CASCADE;
ALTER TABLE Comments ADD CONSTRAINT fk_Comments_Posts_id FOREIGN KEY (post_id) REFERENCES Posts (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Likes ADD CONSTRAINT fk_Likes_Users_id FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Likes ADD CONSTRAINT fk_Likes_Posts_id FOREIGN KEY (post_id) REFERENCES Posts (id) ON DELETE CASCADE ON UPDATE CASCADE;

